name: Dart

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: latest-stable
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - run: flutter pub get
      - run: flutter test

      - name: Print Dart SDK version
        run: dart --version
      
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
